### ISSUE TITLE
Making the App Responsive and Look Awesome on Mobile Devices

### ISSUE THREAD

**Issue by BillyMassey** [ats89/splurgy#1]
On mobile things don't look as good as they could be.

One thing you could look into is to add the "mobile meta tag" to your app, so the responsive effect of Bootstrap actually shows up on Mobile.

Let me know in the comments once you figured that step out :)

**Comment by ats89** [comment]
Hey, I missed this message earlier; I added <meta name="viewport" content="width=device-width"> after the <html> in application.html.erb, and it appears to have made it look better on mobile devices. Was that the right place to put the "mobile meta tag"?

**Comment by BillyMassey** [comment]
Hi there -

It looks like you've added the correct line of code to the application, but typically this line of code is supposed to go between the  <head>  and  </head>  tag.  In most browsers it will work, regardless of where you put it on the page, but I'd suggest moving it there.

Thumbs up on getting the right line of code and making your app look awesome on mobile!  :+1: 

Cheers,
Billy

**Comment by BillyMassey** [comment]
For some reason all of my comment is not appearing. It should read "typically this line of code is supposed to go between the head and head tag" with 
1st "head" surrounded by <   >, and 2nd "head" by </   >
